### ISSUE TITLE
Fix GLIDEIN_DUNESite entries for CMST1 and FermiGrid

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#35]
GLIDEIN_DUNESite for CMStier 1 should be US_FNAL (currently undefined
GLIDEIN_DUNESite for FermiGrid should be US_FNAL_FermiGrid (currently US_FNAL)

**Comment by Andrew-McNab-UK** [comment]
I think it is a bad idea to have a site called just US_FNAL when there is another site called US_FNAL_xyz. People will naturally assume when they see US_FNAL that it covers the whole site. For example, you can create GGUS tickets for the Tier1 ("US_FNAL") but they're not the correct way of reporting problems about the FermiGrid site, yes?

**Comment by kherner** [comment]
See https://support.opensciencegrid.org/a/tickets/71942

**Comment by Andrew-McNab-UK** [comment]
Thanks: OSG have updated their config in GitHub and this has been picked up by justIN and is now being used for the site tests. 

However, where FermiGrid jobs are still run directly rather than through the CE, then GLIDEIN_DUNESite=US_FermiGrid still. Presumably this is set "by hand" somewhere in the FermiGrid HTCondor config? The justIN generic jobs have an override for that, and use US_FNAL-FermiGrid instead, so justIN is ok. For the DUNE global pool, all the jobs will run in glideIns I think? So this mismatch will go away?

**Comment by StevenCTimm** [comment]
We can fix the mocked up glidein dune site in jobs that run direct.  Let me know what it should be.

Steve
________________________________

**Comment by StevenCTimm** [comment]
RITM1633650 filed with my group (High Throughput Computing) to get this done.

**Comment by StevenCTimm** [comment]
This has now been done, closing.
