### ISSUE TITLE
Split US_BNL site into US_BNL-RACF and US_BNL-SDCC

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#96]
Or coordinate with Doug appropriately on the right names
The RACF (ATLAS) nodes we are opportunistic on and they allow singularity in singularity.
The SDCC nodes we have a dedicated allocation on and they don't.

**Comment by Andrew-McNab-UK** [comment]
Do we need to do this? It will not be needed in the next release of justIN, which bases CPU resource management on entries rather than sites.

**Comment by kherner** [comment]
Sounds like we just need to be sure they they have different GLIDEIN_DUNESite names.

**Comment by Andrew-McNab-UK** [comment]
I think we should base this on who the tickets should be sent to. If some random DUNE ops person outside the site needs to submit a ticket, does it go to the same place for both subsites or to the same place? Same place = one site. Different places = two subsites?

Another point is that if the storage at the site has onsite vs offsite differences in Rucio, then the RSE's site attribute should be set to the prefix (eg US_FNAL or US_BNL) rather than a full subsite name (US_FNAL-FermiGrid or US_BNL-SDCC) Then I can make justIN realise this is going on and set the distance to zero for the same prefix ones. But for sites like UK_RAL-Tier1 vs UK_RAL-PPD they really are different sites with separate storages and networking, and the distance is non-zero.

**Comment by StevenCTimm** [comment]
The original suggestion I made because the two sub-sites have differences both in memory and in whether they support user namespaces or not.. the existing unified site showed Justin job scripts failing sometimes and succeeding other times.
I am not sure of the current config of rucio at BNL whether a different port is still necessary inside vs. outside, we have to check that.

**Comment by StevenCTimm** [comment]
Also eventually we are going to want to do as CMS does and have different frontend groups for those sites where we have allocations as opposed to those where we are just opportunistic.. that can make sure we fill our allocated sites first.

**Comment by StevenCTimm** [comment]
JustIN has now split things by entry so we know which entry we are accessing at any point, that should have the same effect as what I asked for above.  Closing this
